name: Routine Matinale Pepite

on:
  schedule:
    - cron: '0 8 * * *' # S'exécute à 8h UTC (9h en France)
  workflow_dispatch: # Permet de le lancer à la main pour tester

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Recupere le code
        uses: actions/checkout@v3

      - name: Installe Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installe les outils
        run: pip install -r requirements.txt

      - name: Execute le scan
        run: python ton_nom_de_fichier.py  # <--- /!\ REMPLACE PAR LE NOM EXACT DE TON SCRIPT .PY

      - name: Enregistre le nouveau JSON
        run: |
          git config --global user.name 'RobotPepite'
          git config --global user.email 'bot@pepite.com'
          git add tinder_shopping_final.json
          git commit -m "MAJ Automatique : Nouvelles pépites" || echo "Rien de neuf"
          git push
